kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: web-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webservers
    spec:
      containers:
      - name: basicwebapp1
        image: hritik555/basicwebapp
        ports:
        - containerPort: 80
